name: Build GUI for Windows XP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-winxp-gui:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      name: checkout

    - run: ./build_gui_winxp.bat
      name: build-xp-gui
